### ISSUE TITLE
How to install? Noob here to cargo and rust...

### ISSUE THREAD

**Issue by reeqbone** [nukeop/cadmium#2]
I did "cargo build" to build the package but when I did  
```
cadmium --input image.png --palette .xres.palette --output test.png'
```
I get 
```
bash: cadmium: command not found
```

**Comment by nukeop** [comment]
To run with cargo, just do
```shell
cargo run -- --input image.png --palette .xres.palette --output test.png'
```

I'm working on an action that will build binaries for all platforms soon.

**Comment by nukeop** [comment]
The release action is ready, you can now just download the binary for your platform from releases.

**Comment by andrewbanchich** [comment]
Alternatively, in the project directory, you can run `cargo install --path .` and it will build and install it on your system. All `cargo build` does is build the binary, which is then available in the `./target` directory.

**Comment by reeqbone** [comment]
Thank you all, I learned how to fix it. I placed cargo in /usr/local/bin and I was able to run it through my terminal.

**Comment by reeqbone** [comment]
[Closed]

**Comment by reeqbone** [comment]
[Sloved]

**Comment by reeqbone** [comment]
sudo dnf close https://github.com/nukeop/cadmium/issues/2

**Comment by reeqbone** [comment]
sudo pacman -Syu https://github.com/nukeop/cadmium/issues/2

**Comment by reeqbone** [comment]
yay -Rncs https://github.com/nukeop/cadmium/issues/2

**Comment by reeqbone** [comment]
sudo apt-get git && git close https://github.com/nukeop/cadmium/issues/2

**Comment by reeqbone** [comment]
Fuck why isnt this working

**Comment by reeqbone** [comment]
Wait nevermind, I just have to close with the comment.
