### ISSUE TITLE
Not working at All (new to rust and it's filestructure)

### ISSUE THREAD

**Issue by namishh** [nukeop/cadmium#3]
i trried running this 
`cadmium --input input.png --palette wave.pallete --output output.png`

wave is custom pallete
pallete -
```#0a1011
#0d1617
#121b1c
#1a1b1c
#d7e0e0
#c5d7d7
#cedcd9
#6fd1d5
#7bd3e0
#659bdb
#739bdf
#df5b61
#deb26a
#dbb476
#6ec587
#c167d7
```

but it throws me a error saying
```thread 'main' panicked at 'byte index 1 is out of bounds of ``', library/core/src/str/mod.rs:107:9```

any help will be appreciated :)

**Comment by nukeop** [comment]
Remove empty lines and spaces from each line

**Comment by namishh** [comment]
it works thanks
